[package]
name = "nebula"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.96"
clap = "4.5.31"
enum_dispatch = "0.3.13"
futures = "0.3.31"
reqwest = "0.12.12"
serde = "1.0.218"
serde_json = "1.0.139"
thiserror = "2.0.11"
tokio = "1.43.0"
